version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker/development/nginx
    ports:
      - "${PORT_FRONTEND}:${PORT_FRONTEND}"
      - "${PORT_API}:${PORT_API}"
    depends_on:
      - frontend
      - api
  frontend:
    build:
      context: frontend/docker/development/nginx
    ports:
      - "${PORT_FRONTEND}:80"
    volumes:
      - ./frontend:/app
  api:
    build:
      context: api/docker/development/nginx
    ports:
      - "${PORT_API}:80"
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm
  api-php-fpm:
    build:
      context: api/docker/development/php-fpm
    volumes:
      - ./api:/app

